services:
  backend:
    build:
      dockerfile: backend.Dockerfile
      context: .
    image: todo-webapp-backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: "postgres"
      DB_NAME: "postgres"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_PORT: "5432"
    ports:
      - "8080:8080"
  postgres:
    image: postgres:17
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./docker/sql_setup.sh:/docker-entrypoint-initdb.d/sql_setup.sh
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"

volumes:
  postgres-data:
