name: backend

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dlang-community/setup-dlang@v2
        with:
          compiler: ldc
      - uses: actions/cache@v4
        with:
          path: ~/.dub
          key: dub-${{ hashFiles('./backend/dub.selections.json') }}
          restore-keys: |
            dub-
      - name: Run lint
        run: make lint-backend
      
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "postgres"
          POSTGRES_DB: "postgres"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: dlang-community/setup-dlang@v2
        with:
          compiler: ldc
      - uses: actions/cache@v4
        with:
          path: ~/.dub
          key: ${{ runner.os }}-dub-${{ hashFiles('./backend/dub.selections.json') }}
          restore-keys: |
            ${{ runner.os }}-dub-
      - name: install postgres dependencies
        run: sudo apt-get update && sudo apt-get -y install libpq-dev
      - name: Run test
        run: make test-backend
