name: frontend

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-only-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jorelali/setup-elm@v6
        with:
          elm-version: 0.19.1
      - name: Build
        run: make build-frontend
